import random

def sorteio_legado():
    lista_legado = list(["Alraunes","Elfos","Minotauros","Netunes","Anões","Daevas","Ursars","Valdraks","Humanos","Delahks","Dreanuns","Kitaris","Orkrashs","Inaris","Seikos","Yuansus","Zaokans","Elementais","Forjados","Kahats'Zas","Vennélis"])
    legado_escolhido = random.choice(lista_legado)
    return legado_escolhido
legado = sorteio_legado()

habil_legado = {
    "Alraunes": "FILHOS DE DARNAWEL: O seu corpo é feito de plantas e vinhas, fazendo com que você não precise se alimentar, precisando apenas de água para sobreviver. Você pode criar pequenos efeitos inofensivos que tenham ligação com a natureza, como o desabrochar de uma flor, um som de um animal, uma lufada de vento, entre outros pequenos efeitos inofensivos que podem ser autorizados pelo Narrador. Além disso, você possui Resistência Mágica [Natureza] e não é afetado por Envenenado.\nESSÊNCIA REVIGORANTE: Uma vez por rodada, ao receber uma regeneração de Pontos de Vida, você aumentará esta regeneração em um valor igual a metade do seu total máximo de Pontos de Energia",
    "Elfos": "SABEDORIA ANTIGA: Você inicia com 3 pontos adicionais a serem distribuídos nos seus Conhecimentos. O seu limite máximo na distribuição dos seus Conhecimentos ainda é 2. Além disso, com uma Ação Simples, você passa a compreender um Idioma sendo falado por um alvo até 10 metros, podendo também falar este mesmo Idioma por 10 minutos. Você pode manter somente um Idioma por vez com este efeito.\nPENSAMENTO CÉLERE: Caso você falhe em teste de Parâmetro, você receberá bônus de +1 no seu próximo teste de Parâmetro. Este efeito não acumula e caso não utilizado é removido em 1 minuto.",
    "Minotautos": "NÔMADE: Você nunca esquece o caminho de trilhas, estradas ou ruínas que já percorreu. Além disso, ao utilizar uma Corrida você utilizará esta Movimentação com o seu total de metros, ao invés da metade. Além disso, você é imune a Lentidão e a Terreno Difícil.\nVISÃO ETÉREA: Com uma Ação Simples você se conecta a um pequeno local que você já tenha visitado (um quarto, sala, saguão, por exemplo), podendo enxergar tudo neste local por 10 minutos. Você pode desfazer este efeito a qualquer momento.",
    "Netunes": "ADAPTAÇÃO DOS OCEANOS: Você respira e enxerga naturalmente dentro e fora d'água, além de não receber penalidades aplicadas pelo Combate Aquático. Em terra, você adapta o seu corpo, transformando a sua cauda em um par de pernas humanoides. Além disso, você consegue se comunicar mentalmente com um alvo até 6 metros de você. Este efeito permanece por 1 minuto ou até você se comunicar mentalmente com outro alvo.\nRECOMPENSA DA CAÇADA: Sempre que você realizar um Acerto Crítico você poderá realizar os seus dois efeitos, ao invés de escolher apenas um.",
    "Anões":"HERANÇA DOS TRÊS IRMÃOS: Você precisa de metade de comida e água para sobreviver, além ignorar a regra de 2 horas adicionais vindos de Repousos caso esteja repousando em um local desconfortável. Você também possui Infravisão. Além disso, enquanto você estiver tocando um objeto mundano de até 1 metro de altura e largura, você poderá modificar a forma física deste objeto. Você também pode utilizar este efeito para reparar um pequeno objeto mundano, contando que a parte danificada não seja maior que 30 centímetros. Este efeito de reparo é permanente, ou até ser quebrado novamente. FORTITUDE AMPLIADA: O seu dado de Pontos de Vida ao criar um personagem e ao receber Pontos de Aprendizado é 1d8, ao invés de 1d6. Caso você opte pelo valor fixo desta rolagem, considere 4, ao invés de 3.",
}